### ISSUE TITLE
Do not understand what the library do

### ISSUE THREAD

**Issue by dimmduh** [rfadeev/unity-forge-anim-callbacks#1]
I can directly call clip.AddEvent()

What does library do?

**Comment by rfadeev** [comment]
Hi,

`AnimationClip.AddEvent` adds animation event to clip timeline. While event is added, it's developers responsibility to ensure function name is set to a proper function on component attached to game object. For that to happen, such component should be attached (hence code should be written for that event purpose).

Library helps to avoid component creation and function management to expose adding animation callback via dedicated method with component and function management happening under hood. So it eases adding animation callbacks from the code without bothering about component management.

Plus it reuses animation events between callbacks if timeline position is the same, so
```csharp
animator.AddClipStartCallback(layerIndex, clipName, ExampleMethod0);
animator.AddClipStartCallback(layerIndex, clipName, ExampleMethod1);
animator.AddClipStartCallback(layerIndex, clipName, ExampleMethod2);
```
would use single clip animation event.

Let me know whether this explanation helps!

**Comment by dimmduh** [comment]
Thanks for great reply!
